# Generated by Django 5.2.4 on 2025-07-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_contactenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='image/'),
        ),
    ]
